// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SensorBackgroundJobs;

#nullable disable

namespace SensorBackgroundJobs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240711022358_AddMeterSensor")]
    partial class AddMeterSensor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SensorBackgroundJobs.Models.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MeterCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("MeterType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("MeterCode")
                        .IsUnique();

                    b.HasIndex("MeterType");

                    b.ToTable("Meters", (string)null);
                });

            modelBuilder.Entity("SensorBackgroundJobs.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<string>("SensorCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("StallId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.HasIndex("MeterId")
                        .IsUnique();

                    b.HasIndex("SensorCode")
                        .IsUnique();

                    b.HasIndex("SensorName");

                    b.HasIndex("StallId");

                    b.ToTable("Sensors", (string)null);
                });

            modelBuilder.Entity("SensorBackgroundJobs.Models.Setting", b =>
                {
                    b.Property<double>("GasUnitPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("InvoicePublishDay")
                        .HasColumnType("integer");

                    b.Property<string>("MQTTIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("SensorIPTemplate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<double>("WaterUnitPrice")
                        .HasColumnType("double precision");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("SensorBackgroundJobs.Models.Stall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoicePublishDay")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StallCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StallFloor")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StallInfo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("StallLot")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StallName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("StallCode")
                        .IsUnique();

                    b.HasIndex("StallFloor");

                    b.HasIndex("StallInfo");

                    b.HasIndex("StallLot");

                    b.HasIndex("StallName");

                    b.ToTable("Stalls", (string)null);
                });

            modelBuilder.Entity("SensorBackgroundJobs.Models.Sensor", b =>
                {
                    b.HasOne("SensorBackgroundJobs.Models.Meter", "Meter")
                        .WithOne("Sensor")
                        .HasForeignKey("SensorBackgroundJobs.Models.Sensor", "MeterId");

                    b.HasOne("SensorBackgroundJobs.Models.Stall", "Stall")
                        .WithMany("Sensors")
                        .HasForeignKey("StallId");

                    b.Navigation("Meter");

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("SensorBackgroundJobs.Models.Meter", b =>
                {
                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SensorBackgroundJobs.Models.Stall", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
