// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SensorBackgroundJobs;

#nullable disable

namespace SensorBackgroundJobs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240710145811_AddSettingsAndStalls")]
    partial class AddSettingsAndStalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SensorBackgroundJobs.Models.Setting", b =>
                {
                    b.Property<double>("GasUnitPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("InvoicePublishDay")
                        .HasColumnType("integer");

                    b.Property<double>("WaterUnitPrice")
                        .HasColumnType("double precision");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("SensorBackgroundJobs.Models.Stall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoicePublishDay")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StallCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StallFloor")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StallInfo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("StallLot")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StallName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("StallCode");

                    b.HasIndex("StallFloor");

                    b.HasIndex("StallInfo");

                    b.HasIndex("StallLot");

                    b.HasIndex("StallName");

                    b.ToTable("Stalls", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
